### ISSUE TITLE
setFloatingButtonEdge is working not correctly on Android

### ISSUE THREAD

**Issue by PEvgeniya** [Instabug/Instabug-React-Native#1045]
### **Steps to Reproduce the Problem**
Init instabug with floating Button invocation event, set button position to the right bottom corner using BugReporting.setFloatingButtonEdge(FloatingButtonPosition.right)

### **Expected behaviour** 
The button is in the right bottom corner (top: 80% of height)

### **Actual behaviour** 
It works just fine as expected on iOS, but on Android it is located not correctly
the height of screen is correct, it is tested with other elements on the screen

### **Instabug integration code**
 `
Instabug.init({
        token: 'INSTABUG_TOKEN',
        invocationEvents: [InvocationEvent.floatingButton],
 });

const height = Dimensions.get('window').height;
BugReporting.setFloatingButtonEdge(FloatingButtonPosition.right, height * 0.8);
`

### **SDK Version**
12.1.0

### React Native, iOS and Android Versions
react-native: "0.72.6",
iOS: "17"
Android:  buildToolsVersion = "33.0.0" minSdkVersion = 23   compileSdkVersion = 33  targetSdkVersion = 33

**Comment by a7medev** [comment]
Hello @PEvgeniya! Thanks for reporting this issue.

This issue is that the values passed to `BugReporting.setFloatingButtonEdge` aren't normalized from React Native values to appropriate values to pass to the native side so the way the number passed is treated differs both Android and iOS.

On Android, it expects the value to be in pixel size (px), not in layout size (dp), and React Native uses layout size by default, so the value returned from `Dimensions` needs to get scaled to be in pixel size which you can achieve using the `PixelRatio` API as below:

```js
const height = Dimensions.get('window').height;

BugReporting.setFloatingButtonEdge(
  FloatingButtonPosition.right,
  PixelRatio.getPixelSizeForLayoutSize(height * 0.8),
);
```

On iOS, it expects the value in layout size which is the default in React Native so you can pass the value from `Dimensions` as is.

The complete code should look something like this (I'm using `Platform` to conditionally normalize the value on Android):

```js
const height = Dimensions.get('window').height;
const offset = 0.8 * height;

BugReporting.setFloatingButtonEdge(
  FloatingButtonPosition.right,
  Platform.OS === 'android' ? PixelRatio.getPixelSizeForLayoutSize(offset) : offset,
);
```

We already have it on our radar to make such APIs behave the same on both iOS and Android without the need for manual normalization from the developer's end, but this is how you can achieve it for now. 🙏🏼

I'll close the issue for now but feel free to reopen it if you're still facing any issues with it.
