### ISSUE TITLE
Images from the gallery are rotated incorrectly

### ISSUE THREAD

**Issue by sammoboi13** [Instabug/Instabug-React-Native#177]
I'm on version 8.0.0 of instabug and 0.56.0 of React Native.

When adding portrait images from the gallery they are rotated onto their side. This is occurring on both Android and iOS.

Is this a known caveat/bug?

**Comment by sammoboi13** [comment]
![screenshot_20180721-103916](https://user-images.githubusercontent.com/11660441/43034369-1a20aa26-8cd3-11e8-9fc1-c1fda9b730a4.png)
![screenshot_20180721-103916](https://user-images.githubusercontent.com/11660441/43034374-2817e2de-8cd3-11e8-882d-15b16d5dda59.png)

Images are taken in portrait, but displayed like this in the interface

**Comment by Korazy** [comment]
That's definitely odd! We'll look into it and get back to you as soon as possible :)

**Comment by Korazy** [comment]
@sammoboi13 does this issue occur for all images being attached? Also, if you take a screenshot, are they also rotated?

**Comment by sammoboi13** [comment]
No it doesn't occur for all images. Screenshots and most downloaded images seem to be fine, and on some devices taking a photo is also ok. This leads me to believe it could be related to the height of the image, as it's potentially only happening on high resolution photos (which will usually just be those taken by the device)

**Comment by Korazy** [comment]
Would you be able to tell me starting from which resolution/dimensions you think this would be occurring on?

**Comment by sammoboi13** [comment]
It is occurring on a Samsung Galaxy S7 which takes pictures ~4000x3000. Also occurs on iPhone 7

**Comment by Korazy** [comment]
Hey @sammoboi13 

After much investigation, while the images definitely shouldn't be rotated, the resolution is bigger than expected so we'll continue to investigate it :)

**Comment by ramiimagdi** [comment]
Hey @sammoboi13, 

I just wanted to let you know that we worked on solving this problem here and it should be fixed on:
**com.instabug.library:instabug:8.0.3.5-SNAPSHOT**

However, it will be released on the next official version for Android SDK.

Also, here's what happened in order to have more input on the whole case:
Some devices (like Samsung S7) rely on EXIF orientation headers. Not all images will have an EXIF orientation header. It depends on whether it is a photo, what sort of camera hardware took the photo, whether the camera app that took the photo rotated the image, etc.

Please let us know if you still have any sort of questions here 😄
