### ISSUE TITLE
<myapp> is not using the latest version of the SDK.

### ISSUE THREAD

**Issue by soumyamishra89** [Instabug/Instabug-React-Native#205]
The latest app version should be used for build. latest instabug android version is 8.0.13

android app version in react-native is older than the available one. The one used in react-native is 8.0.4

**Comment by Korazy** [comment]
Hey @soumyamishra89 

Thanks for reaching out. Every time we release a new version of the react-native SDK we update it to the latest version. However, the releases for the RN SDK version is a few days behind the native android one which is why it's not always the latest one.

**Comment by soumyamishra89** [comment]
@Korazy thank you for the update. Maybe to clear the confusion, all the SDKs should have same version number. The react-native version is updated to 8.0.13 but the android version used in it is 8.0.4

**Comment by Korazy** [comment]
Yes we actually recently updated all versions to 8.0.0. React native used to be on 2, while iOS was on 7 and Android was on 4.

Since each individual SDK has its own bugs however, the last digit will likely always be slightly different but the overall version should remain the same.

**Comment by soumyamishra89** [comment]
Thank you for the clarification.

**Comment by Buthrakaur** [comment]
@Korazy I'm still getting this error (at least on Android), because the gradle file uses `com.instabug.library:instabug:8.0.10`, which is a version from August and 8.0.18 is already available. Wouldn't it be better to make the dependency in line with [the Android docs](https://docs.instabug.com/docs/react-native-user-experience#section-gradle) and use `implementation 'com.instabug.library:instabug:8+'`?
