### ISSUE TITLE
iOS (12.1) - undefined is not an object (evaluating 'Instabug.invocationEventNone')

### ISSUE THREAD

**Issue by sinewave440hz** [Instabug/Instabug-React-Native#234]
### Steps to Reproduce the Problem

I have added instabug-reactnative to an existing project with the standard installation process:

yarn add instabug-reactnative
react-native link instabug-reactnative (no errors)

and imported instabug and used it as follows in the constructor of my Home screen:

```
Instabug.startWithToken('e031182a18be2c8efd82209d94fa28a1', [Instabug.invocationEvent.shake]);
```
### Expected Behavior

Works without crashing

### Actual Behavior

![simulator screen shot - iphone xr - 2019-01-10 at 11 48 04](https://user-images.githubusercontent.com/7300069/50963671-a45e3780-14cd-11e9-8b2a-82c3619fb004.png)

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version

^8.0.20

### React Native, iOS Versions

RN 0.57.7
iOS 12.1
### Device Model
iPhone XR

**Comment by salmamali** [comment]
@sinewave440hz This error is caused if the Instabug post link script is not run successfully. Could you try following the linking steps for iOS here [Instabug-React-Native Manual Linking](https://docs.instabug.com/docs/react-native-integration#section-manual-linking).

**Comment by sinewave440hz** [comment]
Fixed after manual linking, thanks. Saw your updates to the docs too, thanks for that.

**Comment by sinewave440hz** [comment]
However, I want to use my project in CI. This is harder if react-native link is broken for this project. Are there any plans to fix it?

**Comment by salmamali** [comment]
@sinewave440hz 
I'm not sure how this will cause a problem with CI, since linking steps are only done once and its changes are pushed to version control. Could you please clarify the steps you'll be following to use CI exactly?
react-native link being broken is not a known issue, there must have been something that was missing from your local env that caused it to break. You can check the post link script `link.rb` in the repo for more info about this.

**Comment by sinewave440hz** [comment]
Yes, you're quite right. Linking is not an issue in terms of CI. Right now there are issues only with android which I'll deal with elsewhere.
