### ISSUE TITLE
Android release build fails on Windows

### ISSUE THREAD

**Issue by mak12** [Instabug/Instabug-React-Native#312]
### Expected Behavior
The build process finishes successfully
### Actual Behavior
The build process throws the following error:

* What went wrong:
Execution failed for task ':instabug-reactnative:upload_sourcemap'.
> A problem occurred starting process 'command 'echo''

### React Native, iOS and Android Versions
0.57.2
### [Optional] Project That Reproduces the Issue
Every time I try to generate signed apk i get this error. Have also checked [this] issue reported .(https://github.com/Instabug/Instabug-React-Native/issues/288#issue-446668302)

**Comment by alyezz** [comment]
@mak12 thanks for reporting this, we're currently working on a fix.

**Comment by alyezz** [comment]
@mak12  We just Release 8.4.3. Update and let us know if you have any issues

**Comment by RZulfikri** [comment]
Hi, I'm facing this issue, I try 8.4.3 and got this error message:

> Task :instabug-reactnative:upload_sourcemap FAILED
Task ':instabug-reactnative:upload_sourcemap' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:instabug-reactnative:upload_sourcemap (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.001 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instabug-reactnative:upload_sourcemap'.
> execCommand == null!

I'm using command in cmd `gradlew.bat assembleRelease --info`

package.json
"instabug-reactnative": "8.4.3",
"react": "16.8.3",
"react-native": "0.59.3",
