### ISSUE TITLE
Instabug Custom Initialization configuration ignored on Android

### ISSUE THREAD

**Issue by elyalvarado** [Instabug/Instabug-React-Native#393]
### Steps to Reproduce the Problem
1. Integrate instabug-reactnative with custom primary color and welcome message mode
2. On second app opening (see #392) Instabug will show the welcome message despite it being disabled.
3. When reporting an Issue the colors passed are ignored

### Expected Behavior
1. Instabug should not show the welcome message if the mode is disabled.
2. Report Alert and dialog should use primary color

### Actual Behavior
The welcome message dialog is being shown, and the primary color is not being used.

### Instabug integration code
```
Instabug.setPrimaryColor(happyTheme.brandPrimary)
Instabug.setCrashReportingEnabled(false)
NetworkLogger.setEnabled(false)
Instabug.setWelcomeMessageMode(Instabug.welcomeMessageMode.disabled)
Instabug.start('REMOVED_APP_TOKEN', [
  Instabug.invocationEvent.shake,
])
```

### SDK Version
 "instabug-reactnative": "^8.6.3",

### React Native, iOS and Android Versions
"react-native": "0.60.5",

### Device Model
DEVICE: motorola moto g(6) play
OS Level 26

**Comment by HeshamMegid** [comment]
This issue has been fixed in 8.6.4, however, we’ve found an issue in v8.6.3 related to initializing the SDK from Javascript that slipped our testing. v8.6.4 rolls back the changes related to initialization that were included in v8.6.3. This means you’ll have to add the Builder snippet back to your Java code.

We know how inconvenient this is, so please accept our apologies for that. We’re currently working on a fix that would let us bring those initialization changes back.
