### ISSUE TITLE
Cannot fully disable Instabug welcome message

### ISSUE THREAD

**Issue by gilbertl** [Instabug/Instabug-React-Native#542]
### Steps to Reproduce the Problem
1. Call Instabug.setWelcomeMessageMode(2)
2. open up an app setup with Instabug Beta (as opposed to live)

### Expected Behavior
No Instabug welcome messages will appear

### Actual Behavior
Instabug still pops up a "welcome to the beta" message

### Instabug integration code
N/A

### SDK Version
9.1.10

### React Native, iOS and Android Versions
RN 0.64rc-1

### Device Model
iPHone X

**Comment by SaraChicaD** [comment]
I'm also having this issue, were you able to find a Javscript fix or just messing with the Java files?

**Comment by AliAbdelfattah** [comment]
Hi @SaraChicaD, sorry this issue is a bit old, it's been resolved through a different support channel; we haven't been able to reproduce it though. Do you mind creating a new issue where you could share with us the reproduction steps, integration code, and the SDK Version?

I'm assuming you're having this issue on Android while this one was reported for iOS, please correct me if I'm mistaken.
