### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by vinayn-mend** [Instabug/Instabug-React-Native#681]
Does this sdk support the latest Expo managed react native project?

**Comment by AliAbdelfattah** [comment]
@vinayn-mend we don't currently support the managed workflow of Expo.

**Comment by trymbill** [comment]
Might be worth mentioning this in the README, seeing how popular Expo has become in the React Native community.

I just spent 2 days trying to debug why `expo-image-picker`'s `ImagePicker.launchCameraAsync()` resulted in an unhandled promise rejection, stating "User rejected permissions" when they didn't reject them, and turns out simply having `"instabug-reactnative": "^11.0.1"` in my `package.json` (not even initialized) borked the permissions.

**Comment by rohanvasishth** [comment]
Experienced the same thing as @trymbill
