### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference VisualUserStepsHelper.java:2

### ISSUE THREAD

**Issue by dltmd6262** [Instabug/Instabug-React-Native#815]
We recently tried to upgrade to 10.13.0 for Android 12 support but we are experiencing random crashes on screens using setPrivateView

### Steps to Reproduce the Problem
1. Go to a screen that has some text input components set to private with `setPrivateView`
2. Send a bug report with a screenshot attachment (text input components will be blacked out)
3. Go to a different screen with some text input components set to private with `setPrivateView` and do 2 there
4. Come back to the first screen in step 1 and crash.

### Expected Behavior
Should not crash

### Actual Behavior
Crashes with the following stacktrace:

[Crash#1861_v3.144 (2249).txt](https://github.com/Instabug/Instabug-React-Native/files/9816018/Crash.1861_v3.144.2249.txt)

### Instabug integration code

Almost all of the components being blacked out are text input components and are blacked out on componentDidMount

```
for (const ref of [
        this.a,
        this.b,
      ]) {
        if (ref.current) {
          Instabug.setPrivateView(ref.current);
        }
      }
```

### SDK Version
10.13.0

### React Native, iOS and Android Versions
RN = 0.62.3

**Comment by DavidMina96** [comment]
Hi @dltmd6262, 

Thank you for reporting this issue. This crash was fixed in a later version, so can you please update to the latest SDK version accordingly? It includes other fixes and enhancements as well. You can refer to our [migration guide](https://docs.instabug.com/docs/react-native-migration-guide) for the migration steps from versions prior to v11. 

If you still have any questions, please feel free to re-open the issue anytime. We're always happy to help :)

**Comment by dltmd6262** [comment]
Sounds good, I was worried v11 wouldn't fix it but I'll upgrade right now. Thanks alot!
