### ISSUE TITLE
Float button make not possible to inspect/assert text/button under it on iOS

### ISSUE THREAD

**Issue by davydspotnana** [Instabug/Instabug-React-Native#972]
### Steps to Reproduce the Problem

I use a https://maestro.mobile.dev/ E2E framework for testing and in make not possible to use on iOS while float button is enabled 

<table>
<thead>
<tr>
<th>Android</th>
<th>iOS (_no float button_)</th>
<th>iOS (_has float button_)</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<img width="270" src="https://user-images.githubusercontent.com/95620376/234021386-c54b081b-36ba-41b5-8e4a-4da66ff6ade0.png">
</td>
<td>
<img width="270" src="https://user-images.githubusercontent.com/95620376/234021403-d90b2104-1c70-4d0c-b1d7-972aaca67a02.png">
</td>
<td>
<img width="270" src="https://user-images.githubusercontent.com/95620376/234021362-a36b5068-4820-45bc-a016-66da7c81018e.png">
</td>
</tr>
</tbody>
</table>

### Expected Behavior

Float button should block access to element onder it (see: **iOS no float button**)

### Actual Behavior

Float button block access to element under it 

### Instabug integration code

...

### SDK Version

?

### Device Model

?

**Comment by a7medev** [comment]
Hi @davydspotnana! Thanks for reporting this issue. We have encountered this issue before trying to test our SDK with Maestro. The problem is that the floating button is attached to another iOS window which causes Maestro to have problems detecting the app's elements as they are attached to a separate window from the floating button.
A workaround for this is to disable the floating button invocation event while E2E testing with Maestro.
